import json

skilldata = [
				["Programming", 7, 1, "https://en.wikipedia.org/wiki/Computer_programming", "static/programming-ico.png", "Programming/Scripting Languages", "Computer programming is the process of performing a particular computation (or more generally, accomplishing a specific computing result), usually by designing and building an executable computer program. Programming involves tasks such as analysis, generating algorithms, profiling algorithms' accuracy and resource consumption, and the implementation of algorithms (usually in a chosen programming language, commonly referred to as coding).", ""],
				["Scripting", 7, 1, "https://www.geeksforgeeks.org/introduction-to-scripting-languages/", "static/scripting-ico.png", "Programming/Scripting Languages", "A scripting language or script language is a programming language for a runtime system that automates the execution of tasks that would otherwise be performed individually by a human operator. Scripting languages are usually interpreted at runtime rather than compiled.", ""],
				["C", 7, 1, "https://en.wikipedia.org/wiki/C_(programming_language)", "static/c-ico.png", "Programming/Scripting Languages", "C is a general-purpose computer programming language. It was created in the 1970s by Dennis Ritchie, and remains very widely used and influential. By design, C's features cleanly reflect the capabilities of the targeted CPUs. It has found lasting use in operating systems, device drivers, protocol stacks, though decreasingly for application software, and is common in computer architectures that range from the largest supercomputers to the smallest microcontrollers and embedded systems.", ""],
				["C#", 9, 1, "https://en.wikipedia.org/wiki/C_Sharp_(programming_language)", "static/csharp-ico.png", "Programming/Scripting Languages", "C# is a general-purpose, multi-paradigm programming language. C# encompasses static typing, strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented (class-based), and component-oriented programming disciplines]", ""],
				["Java", 8, 1, "https://en.wikipedia.org/wiki/Java_%28programming_language%29", "static/java-ico.png", "Programming/Scripting Languages", "Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible. It is a general-purpose programming language intended to let programmers write once, run anywhere (WORA), meaning that compiled Java code can run on all platforms that support Java without the need to recompile.", ""],
				["Python", 9, 1, "https://en.wikipedia.org/wiki/Python_(programming_language)", "static/python-ico.png", "Programming/Scripting Languages", "Python is a high-level, interpreted, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically-typed and garbage-collected. It supports multiple programming paradigms, including structured, object-oriented and functional programming.", ""],
				["SQL", 7, 1, "https://en.wikipedia.org/wiki/SQL", "static/sql-ico.png", "Programming/Scripting Languages", "SQL is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS), or for stream processing in a relational data stream management system (RDSMS). It is particularly useful in handling structured data, i.e. data incorporating relations among entities and variables.", ""],
				["Powershell", 8, 1, "https://en.wikipedia.org/wiki/PowerShell", "static/powershell-ico.png", "Programming/Scripting Languages", "PowerShell is a task automation and configuration management program from Microsoft, consisting of a command-line shell and the associated scripting language. Initially a Windows component only, known as Windows PowerShell, it was made open-source and cross-platform on 18 August 2016 with the introduction of PowerShell Core. The former is built on the .NET Framework, the latter on .NET Core.", ""],
				["C++", 5, 1, "https://en.wikipedia.org/wiki/C++", "static/cpp-ico.png", "Programming/Scripting Languages", "C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language, or 'C with Classes'. The language has expanded significantly over time, and modern C++ has object-oriented, generic, and functional features in addition to facilities for low-level memory manipulation.", ""],
				["JavaScript", 6, 1, "https://en.wikipedia.org/wiki/JavaScript", "static/js-ico.png", "Programming/Scripting Languages", "JavaScript, often abbreviated JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. Over 97% of websites use JavaScript on the client side for web page behavior, often incorporating third-party libraries. All major web browsers have a dedicated JavaScript engine to execute the code on users' devices.", ""],
				["PHP", 5, 1, "https://en.wikipedia.org/wiki/PHP", "static/php-ico.png", "Programming/Scripting Languages", "PHP is a server scripting language, and a powerful tool for making dynamic and interactive Web pages. PHP is a widely-used, free, and efficient alternative to competitors such as Microsoft's ASP.", ""],
				["HTML", 6, 1, "https://en.wikipedia.org/wiki/HTML", "static/html-ico.png", "Programming/Scripting Languages", "The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.", ""],
				["CSS", 6, 1, "https://en.wikipedia.org/wiki/CSS", "static/css-ico.png", "Programming/Scripting Languages", "Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language such as HTML. CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.", ""],
				["LaTeX", 5, 1, "https://en.wikipedia.org/wiki/LaTeX", "static/latex-ico.png", "Programming/Scripting Languages", "LaTeX is a high-quality typesetting system; it includes features designed for the production of technical and scientific documentation. LaTeX is the de facto standard for the communication and publication of scientific documents.", ""],
				["Ruby", 3, 1, "https://en.wikipedia.org/wiki/Ruby_(programming_language)", "static/ruby-ico.png", "Programming/Scripting Languages", "Ruby is an interpreted, high-level, general-purpose programming language which supports multiple programming paradigms. It was designed with an emphasis on programming productivity and simplicity. In Ruby, everything is an object, including primitive data types. It was developed in the mid-1990s by Yukihiro 'Matz' Matsumoto in Japan.", ""],
				["Go", 4, 1, "https://en.wikipedia.org/wiki/Go_(programming_language)", "static/go-ico.png", "Programming/Scripting Languages", "Go is a statically typed, compiled programming language designed at Google[10] by Robert Griesemer, Rob Pike, and Ken Thompson. It is syntactically similar to C, but with memory safety, garbage collection, structural typing, and CSP-style concurrency. It is often referred to as Golang because of its former domain name, golang.org, but its proper name is Go.", ""],
				["Rust", 2, 1, "https://en.wikipedia.org/wiki/Rust_(programming_language)#:~:text=Rust%20is%20a%20multi-paradigm%20programming%20language%20designed%20for,without%20garbage%20collection%2C%20and%20reference%20counting%20is%20optional.", "static/rust-ico.png", "Programming/Scripting Languages", "Rust is a multi-paradigm, general-purpose programming language. It is designed for performance and safety, especially safe concurrency. Rust is known for enforcing memory safety — that is, that all references point to valid memory — without requiring the use of a garbage collector or reference counting like other memory-safe languages. Memory safety is enforced by a borrow checker, which tracks object lifetime and variable scope as references are passed throughout the program during compilation.[16] Rust can be used for systems programming with mechanisms for low-level memory management,[18] but also offers high-level features such as functional programming.", ""],
				["Bash", 4, 1, "https://en.wikipedia.org/wiki/Bash_(Unix_shell)", "static/bash-ico.png", "Programming/Scripting Languages", "Bash is a Unix shell and command language written by Brian Fox for the GNU Project as a free software replacement for the Bourne shell. First released in 1989, it has been used as the default login shell for most Linux distributions. Bash is a command processor that typically runs in a text window where the user types commands that cause actions. Bash can also read and execute commands from a file, called a shell script.", ""],
				[".NET", 6, 1, "https://en.wikipedia.org/wiki/.NET_Framework", "static/dotnet-ico.png", "Frameworks", ".NET is a free, open-source development platform for building many kinds of apps, such as: Web apps, web APIs, and microservices, Serverless functions in the cloud, Cloud native apps, Mobile apps, Desktop apps, Windows WPF, Windows Forms, Universal Windows Platform (UWP), Games, Internet of Things (IoT), Machine learning, Console apps, and Windows services", ""],
				["Bootstrap", 5, 1, "https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)", "static/bootstrap-ico.png", "Frameworks", "Bootstrap is a free and open-source CSS framework directed at responsive, mobile-first front-end web development. It contains HTML, CSS and (optionally) JavaScript-based design templates for typography, forms, buttons, navigation, and other interface components.", ""],
				["Selenium", 7, 1, "https://en.wikipedia.org/wiki/Selenium_(software)", "static/selenium-ico.png", "Frameworks", "Selenium is an open source umbrella project for a range of tools and libraries aimed at supporting browser automation. It provides a playback tool for authoring functional tests without the need to learn a test scripting language (Selenium IDE). It also provides a test domain-specific language (Selenese) to write tests in a number of popular programming languages, including JavaScript (Node.js), C#, Groovy, Java, Perl, PHP, Python, Ruby and Scala. The tests can then run against most modern web browsers.", ""],
				["Ruby on Rails", 2, 1, "https://en.wikipedia.org/wiki/Ruby_on_Rails", "static/rails-ico.png", "Frameworks", "Rails is a web application development framework written in the Ruby programming language. It is designed to make programming web applications easier by making assumptions about what every developer needs to get started. It allows you to write less code while accomplishing more than many other languages and frameworks.", ""],
				["Django", 3, 1, "https://en.wikipedia.org/wiki/Django_(web_framework)", "static/django-ico.png", "Frameworks", "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers, it takes care of much of the hassle of web development, so you can focus on writing your app without needing to reinvent the wheel.", ""],
				["JQuery", 3, 1, "https://en.wikipedia.org/wiki/JQuery", "static/jquery-ico.png", "Frameworks", "jQuery is a fast, small, and feature-rich JavaScript library. It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers.", ""],
				["Unity Engine", 5, 1, "https://en.wikipedia.org/wiki/Unity_(game_engine)", "static/unity-ico.png", "Frameworks", "Unity is a cross-platform game engine developed by Unity Technologies, first announced and released in June 2005 at Apple Worldwide Developers Conference as a Mac OS X game engine. The engine has since been gradually extended to support a variety of desktop, mobile, console and virtual reality platforms. It is particularly popular for iOS and Android mobile game development and is considered easy to use for beginner developers and is popular for indie game development.", ""],
				["Keras", 2, 1, "https://en.wikipedia.org/wiki/Keras", "static/keras-ico.png", "Frameworks", "Keras is a deep learning API written in Python, running on top of the machine learning platform TensorFlow. It was developed with a focus on enabling fast experimentation. Being able to go from idea to result as fast as possible is key to doing good research.", ""],
				["Data Structures", 7, 1, "https://en.wikipedia.org/wiki/Data_structure", "static/datastructures-ico.png", "Theoretical Knowledge", "A data structure is a particular way of organizing data in a computer so that it can be used effectively. The idea is to reduce the space and time complexities of different tasks.", ""],
				["Algorithm Analysis", 7, 1, "https://en.wikipedia.org/wiki/Analysis_of_algorithms", "static/aa-ico.png", "Theoretical Knowledge", "Algorithm analysis is an important part of computational complexity theory, which provides theoretical estimation for the required resources of an algorithm to solve a specific computational problem. Most algorithms are designed to work with inputs of arbitrary length. Analysis of algorithms is the determination of the amount of time and space resources required to execute it.", ""],
				["PDQ Deploy", 6, 1, "https://www.pdq.com/pdq-deploy/", "static/pdq-ico.png", "Software Solutions", "As your business grows, so do the demands on your IT team. Automating repetitive processes is one of the simplest and most cost-effective ways to maximize efficiency without hiring new personnel. PDQ Deploy serves as an automated patch manager and software deployment tool so you can update more computers in less time.", ""],
				["Notepad++", 7, 1, "https://en.wikipedia.org/wiki/Notepad++", "static/nppp-ico.png", "Software Solutions", "Notepad++ is a text and source code editor for use with Microsoft Windows. It supports tabbed editing, which allows working with multiple open files in a single window. The product's name comes from the C postfix increment operator.", ""],
				["Atom", 8, 1, "https://en.wikipedia.org/wiki/Atom_(text_editor)", "static/atom-ico.png", "Software Solutions", "Atom is a free and open-source text and source code editor for macOS, Linux, and Microsoft Windows with support for plug-ins written in JavaScript, and embedded Git Control. Developed by GitHub, Atom is a desktop application built using web technologies. Most of the extending packages have free software licenses and are community-built and maintained. Atom is based on Electron (formerly known as Atom Shell), a framework that enables cross-platform desktop applications using Chromium and Node.js. Atom was initially written in CoffeeScript and Less, but much of it has been converted to JavaScript.", ""],
				["Microsoft Visual Studio", 7, 1, "https://en.wikipedia.org/wiki/Microsoft_Visual_Studio", "static/visualstudio-ico.png", "Software Solutions", "Microsoft Visual Studio is an integrated development environment (IDE) from Microsoft. It is used to develop computer programs, as well as websites, web apps, web services and mobile apps. Visual Studio uses Microsoft software development platforms such as Windows API, Windows Forms, Windows Presentation Foundation, Windows Store and Microsoft Silverlight. It can produce both native code and managed code.", ""],
				["Eclipse", 7, 1, "https://en.wikipedia.org/wiki/Eclipse_(software)", "static/eclipse-ico.png", "Software Solutions", "Eclipse is an integrated development environment (IDE) used in computer programming. It contains a base workspace and an extensible plug-in system for customizing the environment. It is the second-most-popular IDE for Java development, and, until 2016, was the most popular. Eclipse is written mostly in Java and its primary use is for developing Java applications, but it may also be used to develop applications in other programming languages via plug-ins, including Ada, ABAP, C, C++, C#, Clojure, COBOL, D, Erlang, Fortran, Groovy, Haskell, JavaScript, Julia, Lasso, Lua, NATURAL, Perl, PHP, Prolog, Python, R, Ruby (including Ruby on Rails framework), Rust, Scala, and Scheme", ""],
				["Putty", 7, 1, "https://en.wikipedia.org/wiki/PuTTY", "static/putty-ico.png", "Software Solutions", "PuTTY is a free and open-source terminal emulator, serial console and network file transfer application. It supports several network protocols, including SCP, SSH, Telnet, rlogin, and raw socket connection. It can also connect to a serial port.", ""],
				["Git", 7, 1, "https://en.wikipedia.org/wiki/Git", "static/git-ico.png", "Software Solutions", "Git is software for tracking changes in any set of files, usually used for coordinating work among programmers collaboratively developing source code during software development. Its goals include speed, data integrity, and support for distributed, non-linear workflows (thousands of parallel branches running on different systems).", ""],
				["TEXstudio", 5, 1, "https://en.wikipedia.org/wiki/TeXstudio", "static/texstudio-ico.png", "Software Solutions", "TeXstudio is a cross-platform open-source LaTeX editor. Its features include an interactive spelling checker, code folding, and syntax highlighting. It does not provide LaTeX itself, the user must choose a TeX distribution and install it first.", ""],
				["Oracle VirtualBox", 5, 1, "https://en.wikipedia.org/wiki/VirtualBox", "static/oraclevirtualbox-ico.png", "Software Solutions", "Oracle VM VirtualBox is a type-2 hypervisor for x86 virtualization developed by Oracle Corporation. VirtualBox was originally created by Innotek GmbH, which was acquired by Sun Microsystems in 2008, which was in turn acquired by Oracle in 2010. VirtualBox may be installed on Microsoft Windows, macOS, Linux, Solaris and OpenSolaris. There are also ports to FreeBSD and Genode. It supports the creation and management of guest virtual machines running Windows, Linux, BSD, OS/2, Solaris, Haiku, and OSx86, as well as limited virtualization of macOS guests on Apple hardware.", ""],
				["VMware Workstation", 5, 1, "https://en.wikipedia.org/wiki/VMware_Workstation", "static/vmwareworkstation-ico.png", "Software Solutions", "VMware Workstation Pro (known as VMware Workstation until release of VMware Workstation 12 in 2015) is a hosted hypervisor that runs on x64 versions of Windows and Linux operating systems (an x86-32 version of earlier releases was available); it enables users to set up virtual machines (VMs) on a single physical machine and use them simultaneously along with the host machine. Each virtual machine can execute its own operating system, including versions of Microsoft Windows, Linux, BSD, and MS-DOS.", ""],
				["Microsoft Power BI", 4, 1, "https://en.wikipedia.org/wiki/Microsoft_Power_BI", "static/powerbi-ico.png", "Software Solutions", "Power BI is an interactive data visualization software product developed by Microsoft with a primary focus on business intelligence. It is part of the Microsoft Power Platform. Power BI is a collection of software services, apps, and connectors that work together to turn unrelated sources of data into coherent, visually immersive, and interactive insights. Data may be input by reading directly from a database, webpage, or structured files such as spreadsheets, CSV, XML, and JSON.", ""],
				["Microsoft Office", 8, 1, "https://en.wikipedia.org/wiki/Microsoft_Office", "static/mso-ico.png", "Software Solutions", "Microsoft Office, or simply Office, is a family of client software, server software, and services developed by Microsoft. Initially a marketing term for an office suite (bundled set of productivity applications), the first version of Office contained Microsoft Word, Microsoft Excel, and Microsoft PowerPoint. Over the years, Office applications have grown substantially closer with shared features such as a common spell checker, Object Linking and Embedding data integration and Visual Basic for Applications scripting language. Microsoft also positions Office as a development platform for line-of-business software under the Office Business Applications brand.", ""],
				["Microsoft Power Apps", 3, 1, "https://docs.microsoft.com/en-us/power-apps/powerapps-overview", "static/mspa-ico.png", "Software Solutions", "Power Apps is a suite of apps, services, and connectors, as well as a data platform, that provides a rapid development environment to build custom apps for your business needs. Using Power Apps, you can quickly build custom business apps that connect to your data stored either in the underlying data platform (Microsoft Dataverse) or in various online and on-premises data sources (such as SharePoint, Microsoft 365, Dynamics 365, SQL Server, and so on).", ""],
				["ServiceNow", 6, 1, "https://en.wikipedia.org/wiki/ServiceNow", "static/sn-ico.png", "Software Solutions", "ServiceNow is a platform-as-a-service provider, providing technical management support, such as IT service management, to the IT operations of large corporations, including providing help desk functionality. The company's core business revolves around management of 'incident, problem, and change' IT operational events.", ""],
				["Spiceworks", 3, 1, "https://en.wikipedia.org/wiki/Spiceworks", "static/spiceworks-ico.png", "Software Solutions", "Spiceworks is an online community where users can collaborate and seek advice from one another, and also engage in a marketplace to purchase IT-related services and products. The network is estimated to be used by more than six million IT professionals and 3,000 technology vendors. The company's free proprietary software is written in Ruby on Rails, and runs exclusively on Microsoft Windows. The software discovers IP-addressable devices and includes help desk functionality and an integrated knowledge base.", ""], 
				["Microsoft Azure", 4, 1, "https://en.wikipedia.org/wiki/Microsoft_Azure", "static/azure-ico.png", "Software Solutions", "Microsoft Azure, often referred to as Azure, is a cloud computing service operated by Microsoft for application management via Microsoft-managed data centers. It provides software as a service (SaaS), platform as a service (PaaS) and infrastructure as a service (IaaS) and supports many different programming languages, tools, and frameworks, including both Microsoft-specific and third-party software and systems.", ""],
				["Google Cloud", 2, 1, "https://en.wikipedia.org/wiki/Google_Cloud_Platform", "static/gc-ico.png", "Software Solutions", "Google Cloud Platform (GCP), offered by Google, is a suite of cloud computing services that runs on the same infrastructure that Google uses internally for its end-user products, such as Google Search, Gmail, Google Drive, and YouTube. Alongside a set of management tools, it provides a series of modular cloud services including computing, data storage, data analytics and machine learning. Google Cloud Platform provides infrastructure as a service, platform as a service, and serverless computing environments.", ""],
				["AWS", 2, 1, "https://en.wikipedia.org/wiki/Amazon_Web_Services", "static/aws-ico.png", "Software Solutions", "Amazon Web Services, Inc. (AWS) is a subsidiary of Amazon that provides on-demand cloud computing platforms and APIs to individuals, companies, and governments, on a metered pay-as-you-go basis. These cloud computing web services provide distributed computing processing capacity and software tools via AWS server farms.", ""],
				["Windows 10", 9, 1, "https://en.wikipedia.org/wiki/Windows_10", "static/win10-ico.png", "Operating Systems", "Windows 10 is a major release of Microsoft's Windows NT operating system. It is the direct successor to Windows 8.1, which was released nearly two years earlier. It was released to manufacturing on July 15, 2015, and later to retail on July 29, 2015.", ""],
				["Windows 8", 6, 1, "https://en.wikipedia.org/wiki/Windows_8", "static/win8-ico.png", "Operating Systems", "Windows 8 is a major release of the Windows NT operating system developed by Microsoft. It was released to manufacturing on August 1, 2012; it was subsequently made available for download via MSDN and TechNet on August 15, 2012, and later to retail on October 26, 2012.", ""],
				["Windows 7", 7, 1, "https://en.wikipedia.org/wiki/Windows_7", "static/win7-ico.png", "Operating Systems", "Windows 7 is a major release of the Windows NT operating system developed by Microsoft. It was released to manufacturing on July 22, 2009, and became generally available on October 22, 2009.", ""],
				["Ubuntu Server", 8, 1, "https://en.wikipedia.org/wiki/Ubuntu", "static/ubuntuserver-ico.png", "Operating Systems", "Ubuntu has a server edition that uses the same APT repositories as the Ubuntu Desktop Edition. The differences between them are the absence of an X Window environment in a default installation of the server edition (although one can easily be installed, including Unity, GNOME, KDE or Xfce), and some alterations to the installation process. The server edition uses a screen-mode, character-based interface for the installation, instead of a graphical installation process. This enables installation on machines with a serial or 'dumb terminal' interface without graphics support.", ""],
				["Ubuntu Desktop", 7, 1, "https://en.wikipedia.org/wiki/Ubuntu", "static/ubuntudesktop-ico.png", "Operating Systems", "Ubuntu is a Linux distribution based on Debian and composed mostly of free and open-source software. Ubuntu is officially released in three editions: Desktop, Server, and Core for Internet of things devices and robots. All the editions can run on the computer alone, or in a virtual machine. Ubuntu is a popular operating system for cloud computing, with support for OpenStack.", ""],
				["Debian", 5, 1, "https://en.wikipedia.org/wiki/Debian", "static/debian-ico.png", "Operating Systems", "Debian, also known as Debian GNU/Linux, is a Linux distribution composed of free and open-source software, developed by the community-supported Debian Project, which was established by Ian Murdock on August 16, 1993. The first version of Debian (0.01) was released on September 15, 1993, and its first stable version (1.1) was released on June 17, 1996. The Debian Stable branch is the most popular edition for personal computers and servers. Debian is also the basis for many other distributions, most notably Ubuntu.", ""],
				["Linux Mint", 3, 1, "https://en.wikipedia.org/wiki/Linux_Mint", "static/linuxmint-ico.png", "Operating Systems", "Linux Mint is a community-driven Linux distribution based on Ubuntu (which is in turn based on Debian), bundled with a variety of free and open-source applications. It can provide full out-of-the-box multimedia support for those who choose to include proprietary software such as multimedia codecs.", ""],
				["CrunchBang Plus Plus", 5, 1, "https://en.wikipedia.org/wiki/Crunchbang_Linux", "static/crunchbang-ico.png", "Operating Systems", "CrunchBang Linux (abbreviated #!) was a Linux distribution derived from Debian by Philip Newborough (who is more commonly known by his username, corenominal). CrunchBang was designed to use comparatively few system resources. Instead of a desktop environment it used a customized implementation of the Openbox window manager. Many of its preinstalled applications used the GTK+ widget toolkit. CrunchBang PlusPlus (#!++) was developed in response to Newborough's announcement of the end of CrunchBang. It is currently based on the Debian Bullseye (release 11.1) distribution.", ""],
				["macOS", 4, 1, "https://en.wikipedia.org/wiki/MacOS", "static/osx-ico.png", "Operating Systems", "macOS is a Unix operating system developed and marketed by Apple Inc. since 2001. It is the primary operating system for Apple's Mac computers. Within the market of desktop and laptop computers it is the second most widely used desktop OS, after Microsoft Windows and ahead of Chrome OS.", ""],
				["Kali Linux", 3, 1, "https://en.wikipedia.org/wiki/Kali_Linux", "static/kalilinux-ico.png", "Operating Systems", "Kali Linux is a Debian-derived Linux distribution designed for digital forensics and penetration testing. It is maintained and funded by Offensive Security. Kali Linux has around 600 penetration-testing programs (tools), including Armitage (a graphical cyber attack management tool), Nmap (a port scanner), Wireshark (a packet analyzer), metasploit (penetration testing framework), John the Ripper (a password cracker), sqlmap (automatic SQL injection and database takeover tool), Aircrack-ng (a software suite for penetration-testing wireless LANs), Burp suite and OWASP ZAP web application security scanners, etc.", ""],
				["ITIL", 5, 1, "https://en.wikipedia.org/wiki/ITIL", "static/ITIL-ico.png", "Theoretical Knowledge", "The Information Technology Infrastructure Library (ITIL) is a set of detailed practices for IT activities such as IT service management (ITSM) and IT asset management (ITAM) that focus on aligning IT services with the needs of business.", ""],
				["Windows Server 2012", 4, 1, "https://en.wikipedia.org/wiki/Windows_Server_2012", "static/winserver-ico.png", "Operating Systems", "Windows Server 2012 is the sixth version of the Windows Server operating system by Microsoft, as part of the Windows NT family of operating systems. It is the server version of Windows based on Windows 8 and succeeds Windows Server 2008 R2, which is derived from the Windows 7 codebase, released nearly three years earlier. ", ""],
				["Customer Service", 10, 0, "https://en.wikipedia.org/wiki/Customer_service", "static/customerservice-ico.png", "Soft Skills", "Customer service is the provision of service to customers before, during, and after a purchase. This makes it an important part on the value chain of clients. Each industry requires different levels of customer service, but at the end, the idea of a well performed service is that of increasing revenues. The perception of success of the customer service interactions is dependent on employees 'who can adjust themselves to the personality of the customer'.", ""],
				["Project Management", 5, 0, "https://en.wikipedia.org/wiki/Project_management", "static/projectmanagement-ico.png", "Soft Skills", "Project management is the process of leading the work of a team to achieve all project goals within the given constraints. This information is usually described in project documentation, created at the beginning of the development process. The primary constraints are scope, time, and budget. The secondary challenge is to optimize the allocation of necessary inputs and apply them to meet pre-defined objectives.", "" ],
				["Leadership", 5, 0, "https://en.wikipedia.org/wiki/Leadership", "static/leadership-ico.png", "Soft Skills", "Leadership, both as a research area and as a practical skill, encompasses the ability of an individual, group or organization to 'lead', influence or guide other individuals, teams, or entire organizations.", "" ],
				["Delegation", 4, 0, "https://en.wikipedia.org/wiki/Delegation", "static/delegation-ico.png", "Soft Skills", "Delegation is the assignment of authority to another person (normally from a manager to a subordinate) to carry out specific activities. It is the process of distributing and entrusting work to another person, and therefore one of the core concepts of management leadership. The process involves managers deciding which work they should do themselves and which work should be delegated to others for completion.", "" ],
				["Communication", 9, 0, "https://simple.wikipedia.org/wiki/Communication", "static/communication-ico.png", "Soft Skills", "Communication is when information is passed from a sender to a recipient using a medium. There are different media that can be used: Visual communication, communicating with sounds, communication using touch, using smell, or using writing", "" ],
				["Teamwork", 9, 0, "https://en.wikipedia.org/wiki/Teamwork", "static/teamwork-ico.png", "Soft Skills", "Teamwork is the collaborative effort of a group to achieve a common goal or to complete a task in the most effective and efficient way. This concept is seen within the greater framework of a team, which is a group of interdependent individuals who work together towards a common goal.", "" ],
				["Problem Solving", 9, 0, "https://en.wikipedia.org/wiki/Problem_solving", "static/problemsolving-ico.png", "Soft Skills", "Problem solving is the way by which solutions are developed to remove an obstacle from achieving an ultimate goal. Problems in need of solutions range from basic personal issues of 'how do I turn on this appliance?' to more complex topics in the business and academic fields.", "" ],
				["HIPAA Compliance", 4, 1, "https://compliancy-group.com/what-is-hipaa-compliance/", "static/hipaa-ico.png", "Theoretical Knowledge", "Through a series of interlocking regulatory rules, HIPAA compliance is a living culture that health care organizations must implement into their business in order to protect the privacy, security, and integrity of protected health information.", "" ],
				["Agile Methodology", 6, 1, "https://en.wikipedia.org/wiki/Agile_software_development", "static/agile-ico.png", "Theoretical Knowledge", "In software development, agile practices include requirements discovery and solutions improvement through the collaborative effort of self-organizing and cross-functional teams with their customer(s)/end user(s), adaptive planning, evolutionary development, early delivery, continual improvement, and flexible responses to changes in requirements, capacity, and understanding of the problems to be solved.", "" ],
				["Integrity", 6, 0, "https://en.wikipedia.org/wiki/Integrity", "static/integrity-ico.png", "Soft Skills", "Integrity is the practice of being honest and showing a consistent and uncompromising adherence to strong moral and ethical principles and values. In ethics, integrity is regarded as the honesty and truthfulness or accuracy of one's actions.", "" ],
				["Adaptability", 7, 0, "https://en.wikipedia.org/wiki/Adaptive_performance", "static/adaptability-ico.png", "Soft Skills", "Adaptive performance in the work environment refers to adjusting to and understanding change in the workplace. An employee who is versatile is valued and important in the success of an organization. Employers seek employees with high adaptability, due to the positive outcomes that follow, such as excellent work performance, work attitude, and ability to handle stress. Employees, who display high adaptive performance in an organization, tend to have more advantages in career opportunities unlike employees who are not adaptable to change.", ""],
				[ "Empathy", 6, 0, "https://en.wikipedia.org/wiki/Empathy", "static/empathy-ico.png", "Soft Skills", "Empathy is the capacity to understand or feel what another person is experiencing from within their frame of reference, that is, the capacity to place oneself in another's position.", "" ]
			]
d = {"Skills": []}
for i in range(len(skilldata)):
	obj =	{
				"index": i, "name": skilldata[i][0], "exposure": skilldata[i][1],
				"soft_or_hard": skilldata[i][2], "reference": skilldata[i][3],
				"icon": skilldata[i][4], "category": skilldata[i][5],
				"desc_short": skilldata[i][6], "desc_long": skilldata[i][7]
			}
	d["Skills"].append(obj)

addresses = [ 
			"400 E North St, Jackson, MI 49202", 
			"2003 Horton Rd Suite B, Jackson, MI, 49203",
			"544 Wildwood Ave, Jackson, MI 49201",
			"1903 W Michigan Ave, Kalamazoo, MI 49008", 
			"625 Kenmoor Ave SE, Suite 311, Grand Rapids, MI 49546",
			"515 Eastern Ave, Allegan, MI 49010",
			"2111 Emmons Rd, Jackson, MI 49201",
			"10527 S Sprinkle Rd, Vicksburg, MI 49097"
		]
d["Addresses"] = []
for i in range(len(addresses)):
	obj = { "index": i, "name": addresses[i] }
	d["Addresses"].append(obj)
	
orgs = [
			["City of Jackson: Nixon Water Park", '''Waterpark? Nixon’s got one. Skateboard park? Got that too. Four softball fields, a playground, and a picnic shelter? Let’s just call it - Nixon Park has it all.
			<br>
			Nixon Water Park and Skate Park is a great place to enjoy those hot summer days! Throughout the summer there are gym and swim days, creative themed parties, and customer appreciation discounted rate days at the water park. This water park features a zero-depth pool, along with water slides for the thrill seekers.''', "5177884068", "https://www.cityofjackson.org/1072/Nixon-Skate-Park", "static/coj-logo.png", "static/coj-header.png"],
			
			["Marco's Pizza",'''Marco's Pizza, operated by Marco's Franchising, LLC, is an American restaurant chain and interstate franchise based in Toledo, Ohio, that specializes in Italian-American cuisine. The first store was opened in Oregon, Ohio on Starr Ave. It was founded by Italian immigrant Pasquale "Pat" Giammarco in 1978.''',"5177800100", "https://www.marcos.com/", "static/marcos-logo.png","static/marcos-header.png"],
			
			["Jackson High School",'''Jackson High School is a public high school located near downtown Jackson, Michigan. The school was created in 1908 with the merger of Jackson's West Side and East Side High Schools and moved to its present location in 1927. The school's mascot is the Viking. The athletic teams compete as members of the Southeastern Conference as of 2018. It is a part of the Jackson Public Schools.''',"5178413701","https://www.jpsk12.org/jacksonhs","static/jhs-logo.png","static/jhs-header.png"],
			
			["Western Michigan University", '''Western Michigan University (WMU) is a public research university in Kalamazoo, Michigan. It was established in 1903 by Dwight B. Waldo. Its enrollment, as of the Fall 2019 semester, was 21,470. It is classified among "R2: Doctoral Universities – High research activity".''',"2693872152","https://wmich.edu/studentaffairs","static/wmu-logo.png","static/wmu-header.png"],
			
			["TEKsystems", '''TEKsystems is a United States-based recruitment company that provides information technology staffing solutions. It has offices in North America, Europe, and Asia. Its parent company is Allegis Group.
			<br>
			The company connects information technology professionals with companies seeking their expertise. Specialties covered by TEKsystems include cloud enablement, risk and security, data analytics and insights, enterprise applications, and more. The company has worked in the industries of financial services, healthcare services, communications, and government.''',"6169742560","https://www.teksystems.com/en","static/teksystems-logo.png","static/teksystems-header.png"],
			
			["Perrigo Company",'''Perrigo Company plc is an American Irish–registered manufacturer of private label over-the-counter pharmaceuticals, and while 70% of Perrigo's net sales are from the U.S. healthcare system, Perrigo is legally headquartered in Ireland for tax purposes, which accounts for 0.60% of net sales. In 2013, Perrigo completed the 6th-largest US corporate tax inversion in history when it reregistered its tax status to Ireland to avoid U.S. corporate taxes.''',"2696738451","https://www.perrigo.com/","static/perrigo-logo.png","static/perrigo-header.png"],
			
			["Jackson College",'''Jackson College is a public college in Jackson County, Michigan. It was originally established as Jackson Junior College in 1928. Jackson College has been accredited by the Higher Learning Commission since 1933 and offers 48 associate degrees, certificate programs, and transfer options to Jackson County and Michigan residents. Today, the college has a yearly enrollment of nearly 8,000 students between its several locations.''', "5177968425", "https://www.jccmi.edu/", "static/jc-logo.png", "static/jc-header.png"]
		]

d['Orgs'] = []
for i in range(len(orgs)):
	obj = {
			"index": i,
			"name": orgs[i][0],
			"address": i,
			"phone": orgs[i][2],
			"desc_short": orgs[i][1],
			"website": orgs[i][3],
			"logo": orgs[i][4],
			"image_head": orgs[i][5]
		}
	d['Orgs'].append(obj)
	

jobs = [
			["Lifeguard",0,"2011-06-01","2012-09-01","""Summer job in which lifeguard training and certification from the Red Cross was received to prepare for role. Duties included opening and closing off the pool, providing swim lessons, monitoring activities in the pool area, and identifying any safety issues.""","""Summer job in which lifeguard training and certification from the Red Cross was received to prepare for role. Duties included opening and closing off the pool, providing swim lessons, monitoring activities in the pool area, and identifying any safety issues.""","58,63",0],
			
			["Pizza Delivery Driver",0,"2013-06-01","2013-09-01","""Summer job delivering pizzas to clientele. Cross-trained to be able to not only deliver food to clients and on good customer service practices, but also to prepare and make the food, as well as sanitation and food safety practices.""","""Summer job delivering pizzas to clientele. Cross-trained to be able to not only deliver food to clients and on good customer service practices, but also to prepare and make the food, as well as sanitation and food safety practices.""","58,63",1],
			
			["Offensive Coach",0,"2012-10-01","2013-04-01",""""Volunteer experience coaching high school hockey at alma mater. Duties included assembling offensive line combinations, calling lines during games, and practice planning.""",""""Volunteer experience coaching high school hockey at alma mater. Duties included assembling offensive line combinations, calling lines during games, and practice planning.""","60,61,62",2],
			
			["Helpdesk Technician",0,"2014-09-01","2016-09-01","""Assisted in the management of computer environment by providing physical and remote support to clientele. Experiences with hardware and software troubleshooting, service delivery, project management, knowledge management and asset management were attained. Some additional experience attained in development of software and OS image deployment scripting.""","""Assisted in the management of computer environment by providing physical and remote support to clientele. Experiences with hardware and software troubleshooting, service delivery, project management, knowledge management and asset management were attained. Some additional experience attained in development of software and OS image deployment scripting.""","7,1,28,39,42,47,57,46,58,64,63,62,65",3],
			
			["Service Desk Analyst",0,"2016-10-01","2017-12-01","""Provide quality service support in a large, multi-national business environment. Duties include analyzing, interpreting, and resolving user issues in strong collaboration with a team.""","""Provide quality service support in a large, multi-national business environment. Duties include analyzing, interpreting, and resolving user issues in strong collaboration with a team.""","7,48,39,41,58,64,63,62,68",4],
			
			["Sr. Service Desk Analyst",0,"2017-12-01","2020-03-01","""Provide quality service support in a large, multi-national business environment. Duties include analyzing, interpreting, and resolving user issues in strong collaboration with a team. Solely responsible for maintaining the company's US mobility (cellular) program. Obtained some experience developing automated solutions, primarily in .NET and python, used intrateam to streamline processes.""","""Provide quality service support in a large, multi-national business environment. Duties include analyzing, interpreting, and resolving user issues in strong collaboration with a team. Solely responsible for maintaining the company's US mobility (cellular) program. Obtained some experience developing automated solutions, primarily in .NET and python, used intrateam to streamline processes.""","5,7,20,39,41,46,54,43,40,41,56,58,64,63,62",5],
			
			["Service Desk Supervisor",0,"2020-03-01",None,"""Directly manage a small team of remote service desk staff, providing day-to-day guidance and delegation. Obtained some experiences in project management, interfacing with a wide variety of IT and business stakeholders to address requirements with respect to the team.""","""Directly manage a small team of remote service desk staff, providing day-to-day guidance and delegation. Obtained some experiences in project management, interfacing with a wide variety of IT and business stakeholders to address requirements with respect to the team.""","5,7,20,38,39,46,54,43,40,41,56,58,59,60,61,64,62,66,68,69",5]
			
		]
		
d['Jobs'] = []
for i in range(len(jobs)):
	obj = {
		"index": i,
		"title": jobs[i][0],
		"present": jobs[i][1],
		"date_start": jobs[i][2],
		"date_stop": jobs[i][3],
		"desc_short": jobs[i][4],
		"desc_long": jobs[i][5],
		"skill_ids": jobs[i][6],
		"org": jobs[i][7]
	}
	d['Jobs'].append(obj)
	
contact = ["Tom Esser", 7, "3057109723", "5177401802", "esserth1@outlook.com", "To secure a software engineering role in a team-driven environment that utilizes my exceptional work ethic, accessible demeanor, and technical expertise."]
obj = {
			"index": 0,
			"name": contact[0],
			"address": contact[1],
			"phone1": contact[2],
			"phone2": contact[3],
			"email": contact[4],
			"objective": contact[5]
		}
d['Contact'] = [obj]

edu_data = [
				[2, "High School Diploma", 4.0, None,  "2012-06-01", '''Graduated as class valedictorian. Particpiated in National Honor Society and school sports including hockey and soccer.''', "Placeholder1", "39,60,63"],
				[6, "Associates in Applied Science", 3.2, None,	 "2013-05-01", '''Academic experiences with technical skills, including systems design and analysis, project management, and multiple programming language proficiencies, and soft skills, including, leadership and intrapersonal development and communication.''', "Placeholder2", "0,4,8,10,11,12,29,32,39,59,61,63"],
				[3, "Bachelors in Computer Science", 3.0, None,	 "2021-12-01", '''Academic experiences with theoretical aspects of computer programming, including systems programming and algorithmic logic and design. Further experience attained in software development lifecycle paradigms and project management. Obtained some graduate level experiences with data structures and database management systems design.''', "Placeholder3", "0,1,2,4,6,9,11,12,13,14,17,19,21,23,26,27,29,30,32,33,34,35,36,37,39,49,50,51,53,59,61,64,63"]
		]
d['Education'] = []
for i in range(len(edu_data)):
	obj = {
		"index": i,
		"degree": edu_data[i][1],
		"org": edu_data[i][0],
		"gpa": edu_data[i][2],
		"date_stop": edu_data[i][4],
		"desc_short": edu_data[i][5],
		"desc_long": edu_data[i][6],
		"skill_ids": edu_data[i][7]
	}
	d['Education'].append(obj)

with open('mydata.json', 'w') as f:
	data = json.dumps(d, indent=4, sort_keys=True)
	f.write(data)
